Feat/search menu food
dadahtaufikpermana/restaurant_login_page pull request #2
Opened 2023-02-23 14:25 UTC by dadahtaufikpermana

add image and menu_food_screen.dart with food_card_widget.dart

2023-02-23 15:10 UTC, Rizki-pixel approved these changes

2023-02-23 15:10 UTC, Rizki-pixel commented on lib/menu_food/food_card_widget.dart
> +
a

2023-02-23 15:11 UTC, baguskto requested changes

2023-02-23 15:11 UTC, baguskto commented on lib/menu_food/food_card_widget.dart
> +class FoodCard extends StatelessWidget {
Di bawah class FoodCard kamu tambah parameter. Contoh:
final String title;
trus generate contructornya

2023-02-23 15:11 UTC, baguskto commented on lib/menu_food/food_card_widget.dart
> +                        "Veggie\nTomatto Mix",
Ini kamu replace jadi title

2023-02-23 15:11 UTC, baguskto commented on lib/menu_food/menu_food_screen.dart
> +                  FoodCard(),
Buat jadi gini: 

```
FoodCard(title: "Hihang Hoheng"),

```

2023-02-27 07:05 UTC, mfajarhafidh requested changes

2023-02-27 07:05 UTC, mfajarhafidh commented on lib/menu_food/menu_food_screen.dart
> +class Menu_food_screen extends StatelessWidget {
Saranku kalo nama kelas, pake PascalCase

2023-02-27 07:05 UTC, mfajarhafidh commented on lib/menu_food/menu_food_screen.dart
> +                const InputDecoration(border: InputBorder.none, hintText: ""),
kalo hintTextnya gaada, menurutku dihapus aja

2023-02-27 07:05 UTC, mfajarhafidh commented on pubspec.yaml
> +  #    - assets/image/ic_rectangle3.png
bisa dihapus aja mas kalo ga dipake

2023-02-27 07:15 UTC, Daffayy commented on lib/menu_food/menu_food_screen.dart
> +          child: Form(
Form disini guna nya buat apa ya ka?

2023-02-27 07:23 UTC, dadahtaufikpermana commented on lib/menu_food/menu_food_screen.dart
> +          child: Form(
form awalnya saya gunakan untuk membungkus textfieldForm, tapi ketika saya hapus, ternyata tidak berpengaruh ke fungsi texfield nya, terima kasih sudah bertanya

2023-02-27 07:23 UTC, dadahtaufikpermana commented on pubspec.yaml
> +  #    - assets/image/ic_rectangle3.png
oke siap

2023-02-27 07:26 UTC, dadahtaufikpermana commented on lib/menu_food/menu_food_screen.dart
> +                const InputDecoration(border: InputBorder.none, hintText: ""),
terima kasih koreksinya, mantap

2023-02-27 07:27 UTC, dadahtaufikpermana commented on lib/menu_food/menu_food_screen.dart
> +class Menu_food_screen extends StatelessWidget {
sudah saya perbaiki, terima kasih koreksinya

2023-02-27 07:38 UTC, Daffayy commented on lib/menu_food/menu_food_screen.dart
> +          child: Form(
sama sama ka

2023-02-27 07:45 UTC, merged